# Generated by Django 3.1.6 on 2021-02-17 17:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('publishing_datetime', models.DateTimeField(blank=True, null=True)),
                ('thumbnails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('channel_title', models.URLField()),
            ],
            options={
                'db_table': 'yt_videos',
            },
        ),
    ]
