# Generated by Django 3.1.6 on 2021-02-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubevideos',
            options={'ordering': ['-publishing_datetime']},
        ),
    ]
